### ISSUE TITLE
compatibility with Puppet 8

### ISSUE THREAD

**Issue by corporate-gadfly** [puppetlabs/puppetlabs-tagmail#244]
## Describe the Bug
I wasn't ready to make the move to Puppet 8 yet, however, my yum repository mirror mistakenly showed `puppetserver-8.0.0-1.el8.noarch.rpm` and a `yum update` updated the puppet version.

## Expected Behavior
`tagmail` should run with Puppet 8

## Steps to Reproduce
1. Install Puppet 8 RPM on CentOS 8 Stream
2. Logs will show an error:
```
2023-04-26T10:20:33.989-04:00 ERROR [qtp277425324-72] [puppetserver] Puppet Could not autoload puppet/reports/tagmail: no such file to load -- net/smtp
org/jruby/RubyKernel.java:1057:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
/etc/puppetlabs/code/environments/production/modules/tagmail/lib/puppet/reports/tagmail.rb:6:in `<main>'
org/jruby/RubyKernel.java:1091:in `load'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:78:in `load_file'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:182:in `load'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/instance_loader.rb:54:in `block in loaded_instance'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/concurrent/lock.rb:10:in `synchronize'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/instance_loader.rb:49:in `loaded_instance'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/instance_loader.rb:27:in `block in instance_load'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/report/processor.rb:52:in `block in processors'
```

## Environment
 - Version 8.0.0
 - Platform CentOS 8 Stream
- `mod 'puppetlabs-tagmail',           '4.1.0'`

**Comment by corporate-gadfly** [comment]
Worth mentioning that no errors after downgrading puppetserver to version puppetserver-7.11.0-1.el8.noarch.rpm.

**Comment by corporate-gadfly** [comment]
If it helps any, looks like `net-smtp` is no longer a default gem in [Ruby 3.1](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/).

**Comment by mdechiaro** [comment]
@corporate-gadfly  I came across these problems and this issue, and I found a solution. 

You'll need the `net-smtp` gem installed a puppetserver_gem. You can do this in hiera with stdlib module.

```
---
classes:
- stdlib
stdlib::manage::create_resources:
  package:
    net-smtp: {ensure: installed, provider: puppetserver_gem}
```
Also, this requires an extra path to `ruby-load-path` in `/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf`.

from:
```
ruby-load-path: [/opt/puppetlabs/puppet/lib/ruby/vendor_ruby]
```
to:
```
ruby-load-path: [/opt/puppetlabs/puppet/lib/ruby/vendor_ruby, /opt/puppetlabs/puppet/cache/lib]
```
I found this path fix via #102

**Comment by Matty-uk** [comment]
I've installed the net-smtp package via gem and made the /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf change but it is still failing for me after upgrading to Puppet Server 8.
